meta_name: "Evgenia Manolova"
meta_title: "Evgenia Manolova - HR Consultant"
meta_description: "Want to change your job? Worried about the job interview? Having an HR question but have no one to ask? If the answer is YES,  you are at the right place. "
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"   # required for Twitter Cards
